server:
  port: 8080
spring:
  mail:
      host : smtp.qq.com
      username: 1700689454@qq.com
      password: fjihrwvmzwfkbihb
      properties:
        mail:
          self:
            username: "yummy"
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
              port: 465
      port: 465
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yummy?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    properties:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: MYSQL5InnoDBDialectUTF8
        enable_lazy_load_no_trans: true
    open-in-view: true

admin:
   id: a
   password: a


